
export const SET_CATEGORIES = "SET_CATEGORIES";

export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";
export const ADD_COMMENT_TO_POST = "ADD_COMMENT_TO_POST";
export const VOTE_COMMENT_DOWN = "VOTE_COMMENT_DOWN";
export const VOTE_COMMENT_UP = "VOTE_COMMENT_UP";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_COMMENT_PARENT_OF_ONE = "DELETE_COMMENT_PARENT_OF_ONE";

export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const SET_POST = "SET_POST";
export const VOTE_POST_UP = "VOTE_POST_UP";
export const VOTE_POST_DOWN = "VOTE_POST_DOWN";
export const EDIT_POST = "EDIT_POST";
export const DELETE_POST = "DELETE_POST";